Redirected contacts/memberships to Supabase
CougarCS/CougarCS-Backend pull request #287
Opened 2023-02-25 01:05 UTC by mellophone

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR replaces the CougarCS Cloud post request with Supabase requests.

## Related Tickets & Documents

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

The SUPABASE_URL and SUPABASE_KEY environment variables need to be added to the production deployment.

2023-02-25 18:10 UTC, LeftAutomated requested changes
tasks:
- remove package-lock.json
- refactor lines 167 - 184
- refactor lines 199 - 209
- fix failing unit tests

notes:
- implement the DRY principle, there shouldn't be any duplicated code
- keep the cyclomatic complexity to a minimum, nested if blocks and nested loops increases this
- make sure all automated checks pass

good work so far! let me know if you need clarification on the tasks

2023-02-26 03:11 UTC, Junnyyy reviewed
Looks good! Ensure the Sonar test passes or a workaround is done
Reference my message regarding the Sonar key

2023-02-26 03:15 UTC, Junnyyy requested changes
Slight oversight on my original comment, remember to update the readme sections! 
- Libraries
- .ENV setup

2023-02-26 03:39 UTC, LeftAutomated approved these changes

2023-02-26 03:42 UTC, Junnyyy approved these changes

2023-02-26 03:43 UTC, merged