Dev
CougarCS/CougarCS-Backend pull request #289
Opened 2023-03-18 03:07 UTC by mellophone

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR fixes the contact error where purchasing a membership with an existing psid and a new email would cause the post to fail.

## Related Tickets & Documents

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2023-03-18 03:19 UTC, Junnyyy approved these changes
Looks good! 👍

2023-03-18 03:41 UTC, shubhsheth commented on src/api/routes/payment.js
> +					'ben@cougarcs.com',
Should we keep both emails?

2023-03-18 23:19 UTC, bnleft requested changes
tasks:
- rename `dupViolation` to `isDuplicateContact`
- rename `dupUHID` to `isDuplicateUHID`
- rename `dupEmail` to `isDuplicateEmail`

notes:
- avoid abbreviations
- add prefix/suffix (like `is`, `has`, or `Exists`) to variable names to indicate booleans with its respective relationship to the object

2023-03-23 21:40 UTC, bnleft approved these changes

2023-03-23 21:40 UTC, merged